# Form implementation generated from reading ui file 'd:\Pyhton\Project\test\face_recognition\ui\save_person.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_savewindow(object):
    def setupUi(self, savewindow):
        savewindow.setObjectName("savewindow")
        savewindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        savewindow.setEnabled(True)
        savewindow.resize(318, 391)
        savewindow.setMinimumSize(QtCore.QSize(300, 80))
        savewindow.setWindowOpacity(1.0)
        self.verticalLayout = QtWidgets.QVBoxLayout(savewindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_image = QtWidgets.QLabel(parent=savewindow)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.verticalLayout.addWidget(self.label_image)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=savewindow)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"楷体\";")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name_lineedit = QtWidgets.QLineEdit(parent=savewindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_lineedit.sizePolicy().hasHeightForWidth())
        self.name_lineedit.setSizePolicy(sizePolicy)
        self.name_lineedit.setObjectName("name_lineedit")
        self.horizontalLayout.addWidget(self.name_lineedit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yes_btn = QtWidgets.QPushButton(parent=savewindow)
        self.yes_btn.setStyleSheet("font: 16pt \"楷体\";")
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_2.addWidget(self.yes_btn)
        self.no_btn = QtWidgets.QPushButton(parent=savewindow)
        self.no_btn.setStyleSheet("font: 16pt \"楷体\";")
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout_2.addWidget(self.no_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(savewindow)
        QtCore.QMetaObject.connectSlotsByName(savewindow)

    def retranslateUi(self, savewindow):
        _translate = QtCore.QCoreApplication.translate
        savewindow.setWindowTitle(_translate("savewindow", "输入存储的姓名"))
        self.label.setText(_translate("savewindow", "人物姓名："))
        self.yes_btn.setText(_translate("savewindow", "确定"))
        self.no_btn.setText(_translate("savewindow", "取消"))
